name: Publish to NPM

permissions:
  id-token: write  # Required for trusted publishing
  contents: write
  attestations: write

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Type of version bump'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  bump-version-pr:
    uses: maplibre/reusable-workflows/.github/workflows/create-bump-version-pr.yml@main
    with:
      version: ${{ github.event.inputs.release_type }}
